version: "3.4"
services:
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    hostname: service-registry
    volumes:
     - ./consul/server.json:/consul/config/server.json:ro
    networks:
      - assignment
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - assignment
    command: "agent"
  
  api-gateway:
    container_name: assignment-api-gateway
    depends_on:
      - consul-server
    networks:
      - assignment
    build:
      context: .
      dockerfile: APIGateway.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports: 
      - "4012:80" 
      
  consumer-api:
    container_name: assignment-consumer-api
    hostname: consumerApi
    depends_on:
        - consul-server
    networks:
      - assignment
    build:
      context: .
      dockerfile: ConsumerAPI.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://consumerApi
    ports: 
      - "4011:80"

  admin-api:
    container_name: assignment-admin-api
    hostname: adminApi
    depends_on:
        - consul-server
    networks:
      - assignment
    build:
      context: .
      dockerfile: AdminAPI.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://adminApi
    ports: 
      - "4013:80" 

  service-provider-api:
    container_name: assignment-service-provider-api
    hostname: serviceProviderApi
    depends_on:
        - consul-server
    networks:
      - assignment
    build:
      context: .
      dockerfile: ServiceProviderAPI.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://serviceProviderApi
    ports: 
      - "4014:80" 

  booking-api:
    container_name: assignment-booking-api
    hostname: bookingApi
    depends_on:
        - consul-server
    networks:
      - assignment
    build:
      context: .
      dockerfile: BookingAPI.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://bookingApi
     - ServiceProviderAPIURL =http://serviceProviderApi
    ports: 
      - "4015:80"
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
        RABBITMQ_ERLANG_COOKIE: guest
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
      - assignment
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq

networks:
  assignment:
    driver: bridge